# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(280, 302)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 280, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuCalls = QtWidgets.QMenu(self.menuBar)
        self.menuCalls.setObjectName("menuCalls")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setEnabled(True)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setEnabled(True)
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(":/Image/AnpassenIcon.png"),
        #                QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.actionConnect.setIcon(icon)
        self.actionConnect.setObjectName("actionConnect")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        # icon1 = QtGui.QIcon()
        # icon1.addPixmap(QtGui.QPixmap(":/Image/application-exit.png"),
        #                 QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.actionQuit.setIcon(icon1)
        self.actionQuit.setObjectName("actionQuit")
        self.menuCalls.addAction(self.actionConnect)
        self.menuCalls.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuCalls.menuAction())
        self.mainToolBar.addAction(self.actionConnect)
        self.mainToolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "USB Simulator"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menuCalls.setTitle(_translate("MainWindow", "Calls"))
        self.actionConnect.setText(_translate("MainWindow", "Anpassen"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


# import Icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
