# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mibloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MIBloader(object):
    def setupUi(self, MIBloader):
        MIBloader.setObjectName("MIBloader")
        MIBloader.resize(250, 250)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MIBloader)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LB_rename = QtWidgets.QLabel(MIBloader)
        self.LB_rename.setObjectName("LB_rename")
        self.horizontalLayout.addWidget(self.LB_rename)
        self.lineEdit_rename = QtWidgets.QLineEdit(MIBloader)
        self.lineEdit_rename.setObjectName("lineEdit_rename")
        self.horizontalLayout.addWidget(self.lineEdit_rename)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LB_source = QtWidgets.QLabel(MIBloader)
        self.LB_source.setObjectName("LB_source")
        self.horizontalLayout_2.addWidget(self.LB_source)
        self.LE_source = QtWidgets.QLineEdit(MIBloader)
        self.LE_source.setObjectName("LE_source")
        self.horizontalLayout_2.addWidget(self.LE_source)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LB_destination = QtWidgets.QLabel(MIBloader)
        self.LB_destination.setObjectName("LB_destination")
        self.horizontalLayout_3.addWidget(self.LB_destination)
        self.LE_destination = QtWidgets.QLineEdit(MIBloader)
        self.LE_destination.setObjectName("LE_destination")
        self.horizontalLayout_3.addWidget(self.LE_destination)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.LB_usbfreespace = QtWidgets.QLabel(MIBloader)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.LB_usbfreespace.setFont(font)
        self.LB_usbfreespace.setObjectName("LB_usbfreespace")
        self.verticalLayout.addWidget(self.LB_usbfreespace)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LB_tempopath = QtWidgets.QLabel(MIBloader)
        self.LB_tempopath.setObjectName("LB_tempopath")
        self.horizontalLayout_4.addWidget(self.LB_tempopath)
        self.LE_TempoPath = QtWidgets.QLineEdit(MIBloader)
        self.LE_TempoPath.setObjectName("LE_TempoPath")
        self.horizontalLayout_4.addWidget(self.LE_TempoPath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.LB_TampoPathSpace = QtWidgets.QLabel(MIBloader)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.LB_TampoPathSpace.setFont(font)
        self.LB_TampoPathSpace.setObjectName("LB_TampoPathSpace")
        self.verticalLayout_2.addWidget(self.LB_TampoPathSpace)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(MIBloader)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(MIBloader)
        self.buttonBox.accepted.connect(MIBloader.accept) # type: ignore
        self.buttonBox.rejected.connect(MIBloader.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MIBloader)

    def retranslateUi(self, MIBloader):
        _translate = QtCore.QCoreApplication.translate
        MIBloader.setWindowTitle(_translate("MIBloader", "Dialog"))
        self.LB_rename.setText(_translate("MIBloader", "Rename"))
        self.LB_source.setText(_translate("MIBloader", "Source (url)"))
        self.LB_destination.setText(_translate("MIBloader", "Destination"))
        self.LB_usbfreespace.setText(_translate("MIBloader", "Free sapce: -"))
        self.LB_tempopath.setText(_translate("MIBloader", "TempoPath"))
        self.LB_TampoPathSpace.setText(_translate("MIBloader", "Free space: -"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MIBloader = QtWidgets.QDialog()
    ui = Ui_MIBloader()
    ui.setupUi(MIBloader)
    MIBloader.show()
    sys.exit(app.exec_())
