# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mibloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import shutil
import sys
import urllib

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MIBloader(object):
    def setupUi(self, MIBloader):
        MIBloader.setObjectName("MIBloader")
        MIBloader.resize(238, 183)
        self.verticalLayout = QtWidgets.QVBoxLayout(MIBloader)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_rename = QtWidgets.QLineEdit(MIBloader)
        self.lineEdit_rename.setObjectName("lineEdit_rename")
        self.gridLayout.addWidget(self.lineEdit_rename, 0, 1, 1, 1)
        self.LE_source = QtWidgets.QLineEdit(MIBloader)
        self.LE_source.setObjectName("LE_source")
        self.gridLayout.addWidget(self.LE_source, 1, 1, 1, 1)
        self.LB_usbfreespace = QtWidgets.QLabel(MIBloader)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.LB_usbfreespace.setFont(font)
        self.LB_usbfreespace.setObjectName("LB_usbfreespace")
        self.gridLayout.addWidget(self.LB_usbfreespace, 3, 1, 1, 1)
        self.LB_TampoPathSpace = QtWidgets.QLabel(MIBloader)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.LB_TampoPathSpace.setFont(font)
        self.LB_TampoPathSpace.setObjectName("LB_TampoPathSpace")
        self.gridLayout.addWidget(self.LB_TampoPathSpace, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LE_destination = QtWidgets.QLineEdit(MIBloader)
        self.LE_destination.setObjectName("LE_destination")
        self.horizontalLayout_2.addWidget(self.LE_destination)
        self.TB_browser1 = QtWidgets.QToolButton(MIBloader)
        self.TB_browser1.setObjectName("TB_browser1")
        self.horizontalLayout_2.addWidget(self.TB_browser1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LE_TempoPath = QtWidgets.QLineEdit(MIBloader)
        self.LE_TempoPath.setObjectName("LE_TempoPath")
        self.horizontalLayout.addWidget(self.LE_TempoPath)
        self.TB_browser2 = QtWidgets.QToolButton(MIBloader)
        self.TB_browser2.setObjectName("TB_browser2")
        self.horizontalLayout.addWidget(self.TB_browser2)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.LB_rename = QtWidgets.QLabel(MIBloader)
        self.LB_rename.setObjectName("LB_rename")
        self.gridLayout.addWidget(self.LB_rename, 0, 0, 1, 1)
        self.LB_source = QtWidgets.QLabel(MIBloader)
        self.LB_source.setObjectName("LB_source")
        self.gridLayout.addWidget(self.LB_source, 1, 0, 1, 1)
        self.LB_destination = QtWidgets.QLabel(MIBloader)
        self.LB_destination.setObjectName("LB_destination")
        self.gridLayout.addWidget(self.LB_destination, 2, 0, 1, 1)
        self.LB_tempopath = QtWidgets.QLabel(MIBloader)
        self.LB_tempopath.setObjectName("LB_tempopath")
        self.gridLayout.addWidget(self.LB_tempopath, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(MIBloader)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(MIBloader)
        self.buttonBox.accepted.connect(MIBloader.accept) # type: ignore
        self.buttonBox.rejected.connect(MIBloader.reject) # type: ignore
        self.TB_browser1.clicked.connect(lambda: self.resetpath(self.LE_destination,self.LB_usbfreespace))
        self.TB_browser2.clicked.connect(lambda: self.resetpath(self.LE_TempoPath,self.LB_TampoPathSpace))
        QtCore.QMetaObject.connectSlotsByName(MIBloader)

    def retranslateUi(self, MIBloader):
        _translate = QtCore.QCoreApplication.translate
        MIBloader.setWindowTitle(_translate("MIBloader", "Dialog"))
        self.LE_TempoPath.setText(_translate("MIBloader", "{}".format(os.getcwd())))
        self.LB_TampoPathSpace.setText(_translate("MIBloader", "Free space: {} G".format(self.getfreespace(self.LE_TempoPath.text()))))
        self.LB_usbfreespace.setText(_translate("MIBloader", "Free sapce: -"))
        self.TB_browser1.setText(_translate("MIBloader", "..."))
        self.TB_browser2.setText(_translate("MIBloader", "..."))
        self.LB_rename.setText(_translate("MIBloader", "Rename"))
        self.LB_source.setText(_translate("MIBloader", "Source (url)"))
        self.LB_destination.setText(_translate("MIBloader", "Destination"))
        self.LB_tempopath.setText(_translate("MIBloader", "TempoPath"))
    
    def download(self, url):
        print(url)

    def bytesto(self, bytes, to , bsize=1024):
        '''
        convert bytes to megabytes, etc
        '''
        a = {'k' : 1, 'm': 2, 'g' : 3, 't' : 4, 'p' : 5, 'e' : 6 }
        r = float(bytes)
        for _ in range(a[to]):
            r = r / bsize
        return round(r,2)

    def getfreespace(self, path):
        '''
        get current disk free space, return value in gigabyte
        '''
        stat = shutil.disk_usage(path)
        print(path)
        freesp = self.bytesto(bytes=stat.free, to = 'g')
        return freesp
    
    def openfolder(self):
        '''
        open browser, return selected folder path
        '''
        folderpath = QFileDialog.getExistingDirectory(parent=None, caption="select folder", directory= "{}".format(os.path.expanduser("~/Desktop")))
        return folderpath

    def resetpath(self, LineE, LB):
        '''
        get new path
        rewrite new path in line editor
        get free space of new path
        rewrite free space in label
        '''
        newpath = self.openfolder()
        LineE.setText(newpath)
        LB.setText("Free space: {} G".format(self.getfreespace(newpath)))






if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MIBloader = QtWidgets.QDialog()
    ui = Ui_MIBloader()
    ui.setupUi(MIBloader)
    MIBloader.show()
    sys.exit(app.exec_())
